In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [2]:
type(arr1)

numpy.ndarray

In [3]:
arr1.shape

(5,)

In [5]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1, 5)

array([[1, 2, 3, 4, 5]])

In [10]:
arr2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])

In [11]:
arr2.shape

(2, 5)

In [12]:
arr2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [14]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [19]:
arr.ndim

2

In [20]:
arr.size

6

In [21]:
arr.dtype

dtype('int64')

In [22]:
arr.itemsize

8

In [24]:
# numpy vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10, 20, 30, 40, 50])

print("Addition:", arr1 + arr2)
print("Subtraction", arr1 - arr2)
print("Multiplication", arr1 * arr2)
print("Division", arr1 / arr2)

Addition: [11 22 33 44 55]
Subtraction [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]
Division [0.1 0.1 0.1 0.1 0.1]


In [25]:
# universal functions

arr = np.array([2,3,4,5,6])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [26]:
# slicing and indexing

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
print(arr[0][1])

2


In [37]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [38]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [39]:
# modify array elements

arr[0,0] = 100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [40]:
arr[1:] = 100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [41]:
# statistical concepts - normalization
# mean of 0 and std of 1

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)
normalized_data = (data - mean) / std_dev
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [42]:
np.mean(normalized_data)

np.float64(0.0)

In [43]:
np.std(normalized_data)

np.float64(0.9999999999999999)

In [44]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(np.mean(arr))

5.5


In [45]:
# logical operations

data = arr

data > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [50]:
data[(data > 5) & (data <= 8)]

array([6, 7, 8])