In [1]:
import numpy as np

In [2]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4], [5, 6], [7,8]]])

In [3]:
a1D

array([1, 2, 3, 4])

In [4]:
a2D

array([[1, 2],
       [3, 4]])

In [5]:
a3D

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [6]:
a = np.array([2, 3, 4], dtype=np.uint32)
b = np.array([5, 6, 7], dtype=np.uint32)
c_unsigned32 = a - b

In [7]:
c_unsigned32

array([4294967293, 4294967293, 4294967293], dtype=uint32)

In [8]:
c_signed32 = a - b.astype(np.int32)

In [9]:
c_signed32

array([-3, -3, -3])

In [10]:
c_signed32.dtype

dtype('int64')

In [11]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [13]:
np.diag([[1,2,3,4,5]])

array([1])

In [14]:
np.vander(np.linspace(1, 5, 5), 3)

array([[ 1.,  1.,  1.],
       [ 4.,  2.,  1.],
       [ 9.,  3.,  1.],
       [16.,  4.,  1.],
       [25.,  5.,  1.]])

In [22]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
np.random.default_rng(42).random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [25]:
np.indices((3,3,))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [28]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
arr3 = np.array([[13,14,15],[16,17,18]])

arr = np.vstack((arr1, arr2, arr3))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])