In [1]:
import numpy as np

In [2]:
a = np.arange(2, 10)

In [7]:
a[(1)]

SyntaxError: invalid syntax (3085562947.py, line 1)

In [8]:
a[1:5]

array([3, 4, 5, 6])

In [14]:
arr_lst = [[1,2,3], [4,5,6]]
arr = np.array(arr_lst)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr.shape

(2, 3)

In [18]:
arr[1:2]

array([[4, 5, 6]])

In [19]:
x = np.array([[[1],[2],[3]], 
              [[4],[5],[6]]])
x.shape

(2, 3, 1)

In [24]:
x[:,:,0:]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [25]:
obj = slice(1, 2)
x[obj]

array([[[4],
        [5],
        [6]]])

In [26]:
x[..., None]

array([[[[1]],

        [[2]],

        [[3]]],


       [[[4]],

        [[5]],

        [[6]]]])

In [27]:
x[:, np.newaxis, :, :]

array([[[[1],
         [2],
         [3]]],


       [[[4],
         [5],
         [6]]]])

In [28]:
x = np.arange(5)
x + x

array([0, 2, 4, 6, 8])

In [29]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [31]:
x[np.newaxis, :]

array([[0, 1, 2, 3, 4]])

In [32]:
x[:, np.newaxis] + x[np.newaxis, :]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])